### ISSUE TITLE
annotations id 错误。

### ISSUE THREAD

**Issue by huaifeng1993** [Weifeng-Chen/DL_tools#1]
你好，感谢提供代码。我在使用的时候发现annotatios中的id 对应的变量i没有相对应的计算，这样在使用pycocotools读取时会出错。
‘’‘
dataset['annotations'].append({
                'area': width * height,
                'bbox': [x1, y1, width, height],
                'category_id': int(cls_id),
                'id': i,
                'image_id': k,
                'iscrowd': 0,
                # mask, 矩形是从左上角点按顺时针的四个顶点
                'segmentation': [[x1, y1, x2, y1, x2, y2, x1, y2]]
            })
‘’‘

**Comment by Weifeng-Chen** [comment]
感谢提醒，我后来也发现了这个问题，我会更新一下这个代码的。

**Comment by Weifeng-Chen** [comment]
已解决。
