### ISSUE TITLE
圖片標記數量

### ISSUE THREAD

**Issue by up198** [Weifeng-Chen/DL_tools#4]
您好我想請問:
1.yolo2coco這份轉換code支援一張圖片還有多個物件 txt檔有對應各物件的眶嗎
還是說他只能一張圖片 一個標記框呢

**Comment by Weifeng-Chen** [comment]
> 您好我想請問: 1.yolo2coco這份轉換code支援一張圖片還有多個物件 txt檔有對應各物件的眶嗎 還是說他只能一張圖片 一個標記框呢

支持的
