### ISSUE TITLE
語意分割的YOLO如何轉COCO

### ISSUE THREAD

**Issue by ghost** [Weifeng-Chen/DL_tools#5]
作者你好
由於yolov5跟yolov7都有出了語意分割(segmentation)，因此save_txt的內容，就不像傳統的只有bbox xywh值
而是有多個點組成的polygon

不曉得作者您能否做一個polygon的yolo(txt)轉COCO (json)方式
謝謝

**Comment by Weifeng-Chen** [comment]
> 作者你好 由於yolov5跟yolov7都有出了語意分割(segmentation)，因此save_txt的內容，就不像傳統的只有bbox xywh值 而是有多個點組成的polygon
> 
> 不曉得作者您能否做一個polygon的yolo(txt)轉COCO (json)方式 謝謝

好久没做detection相关的了，这边就没维护了。 当然，也欢迎你写一份然后提交PR。

**Comment by ghost** [comment]
你好
這方面我也不是寫CODE高手，我只能提供相關yolo segmentation 檔案給你參考
讓你打開TXT檔，看它內容長怎樣
https://universe.roboflow.com/chonnam-national-university/crack-bphdr/dataset/1

下載時候，麻煩選擇yolov5 or v7 pytorch，裡面就是txt了
